[package]
name = "goldilocks-json-fmt"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
# None at all!

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "format"
harness = false
